language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chooslr/tumblrinbrowser
    branch: publish
  api_key:
    secure: KRf4gd0N3KQ0qY9wBMu3Yxst3ukyefA1QgG0wZwFa7NO+hPKgr3+OTJemyb4QZ9HKFY16EkqSk35uxYL2jtfaD5xAiMjw2TZWrTPyhvQ1x7rQuHKNcAqiKSJfpagcuIOLC8mmK1N8NN7qX7g0+RgapdKGe4JafX8kQlU9PHWmDOZ2HgEiMAZ549946hn49mps73FW7Ya5Xt2MM5np9QK8KP3amqwpbfjQU0gbf1vjd38fSeuXDPh7/q0PHqObsl0wyPnSBI8W0vDrsAnKX5qd0TpFC4yZfzK3GBTtEztOhMGwvsATzI/FJrdAbDZswM38ESy5ykkopCVzp6wLrDdWRYRTRvABK2xaE/G8HUZdhzl9U/33bG+j1X8zzulfnTt71CUzpF77c8VyZKdfoXDJ9n/In3wK25DxgCdAc5YWeDnmEgV91Zh2oUHpGoPlBpTUxHU+/ufyu1iyuGeQEUW96rdMxFtosyyyBehpfmRgcNrXpMS7Hvo4DKsnUdLBjt9kDJTPb3KCVmXUunXo8HBqZKLhKnFP/tbV5lkp8rKMX+ZUgOzJps1ETvuzATQJcHDyypthPe9D02Q2aJnW9YJiMhjfd/XPKDN4XYBjKjL+Ox+mUQr241DD9IvwNUSZ+S8vwF+mELXio4vuxhtS6Mg0VeRu+dNkpVsSyqN/sfHVu4=
