language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chooslr/tumblrinbrowser
    branch: publish
  api_key:
    secure: ZFJpN9hjqLi4tKAI+ryFrC+5Q6evL5Qrac+iSJOV3ibmzsxC8LXeh5Lqr9jTN501EW4EWnghJCWQcHHTTVUvuglQZ6QHCfqCDBEp/bwqS7W8AqTXwymaSD8oz7b5j2xnKB6Qwif58Qc7Q6pA8ImgS+FWlPuPMddrzMpuLxsnpYyzTptpF7Vrvm97lmK7hTbdcfJ0W+XdXenFVMm9v0RnuqTFf2EhEUIoKFAX/Owffh8uh9VkqOdosaxg1Dt21BGmPsXcSMWmZFMP/FfSHhty2iFB3pFukekEsZw5lHMRbFS8hFctR441fVs4+RX7x7FzJtGFAJURQveCLXquWhfyvIzBhLxgbHVGVY2FBptwVhG0KbzRgzwqooq7GxcIPwxmXwR8uavi6NNmYoNXWuFy96vA27wuVgypQUdTfSNmJ2J87WMs2VhynmNYtuKqBf85KtmOjhELF06/4siJp6hpY7feONrNXNAuC1ysAHbXGoXMyIDfyCSF7GoWXj0hRVxAmdxUNaW8h8AAevIbd++phUV21xkWGYkUrd2AKpbTSDV8em4FHkIjNhJTQKABcfPhsq4f9KQDN8ALCFZGfNUTXASaJ2lIvaiGnBQkZXZOTUJbdWqtffxbS3VXyKAhA8nO7WrOPBZtC7mLYjQim4Aa8Z9hy8fyf4/Nd28Nh0o2jP4=
